<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\LoginPage.html">
      <LogicalName>KevinZonda.Terminal.Server.Login/LoginPage.html</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
